#!/usr/bin/env bash
languages=`echo "rust c cpp lua" | tr ' ' '\n'`
core_utils=`echo "xargs find mv sed awk" | tr ' ' '\n'`
# selected=`cat ~/.tmux-cht-languages ~/.tmux-cht-command | fzf`
selected=`echo "$languages\n$core_utils" | fzf`

if [[ -z $selected ]]; then
    exit 0
fi

read -p "Enter Query: " query

# if grep -qs "$selected" ~/.tmux-cht-languages; then
if printf $languages | grep -qs $selected; then
    query=`echo $query | tr ' ' '+'`
    # tmux neww bash -c "echo \"curl cht.sh/$selected/$query/\" & curl cht.sh/$selected/$query & while [ : ]; do sleep 1; done"
    tmux neww bash -c "curl cht.sh/$selected/$query | less"
else
    query=`echo $query | tr ' ' '+'`
    tmux neww bash -c "curl cht.sh/$selected~$query | less"
fi
